### ISSUE TITLE
[Enhancement] Restrict account creation

### ISSUE THREAD

**Issue by Interpause** [liusida/ComfyUI-Login#10]
Hi, I would like to use this as a basic way to only let specific people use my containerized ComfyUI server. As such, would it be possible to restrict account creation? That way, I can control access by handing out account credentials.

**Comment by Interpause** [comment]
nvm i misunderstood, so the account creation is one-time only for one account, that works fine for my case. i'll leave the issue open though if you think its worth. even though its still single rather than multi-user, having different credentials for different people makes it easy to cut access rather than resetting the password when you want to cut access.

**Comment by liusida** [comment]
And just FYI, I have multiple containers, each with ComfyUI installed, on my 4090 machine. That's my version of "multi-user" xD
