### ISSUE TITLE
Logout for new UI

### ISSUE THREAD

**Issue by syllebra** [liusida/ComfyUI-Login#23]
Hello and thank you for this extension.

A tiny small issue occurs when we use the new UI: logout button is not visible anymore. I had to do it for my custom node too, it's not very much.
If I find time I will mak a PR.

Good luck!

**Comment by syllebra** [comment]
This is the compatible code in logout.js:

`async setup() {
		await new Promise(resolve => setTimeout(resolve, 500)); // Delay for 0.5 second before appending the Logout button to the menu, ensuring it is added last.

		function logout(){
			let workflowData = localStorage.getItem('workflow'); // Save the workflow data
			localStorage.clear(); // Clear all items in localStorage
			localStorage.setItem('workflow', workflowData); // Restore the workflow data

			sessionStorage.clear(); // If you use sessionStorage
			window.location.href = "/logout"; 
		}

		// Old interface
		const menu = document.querySelector(".comfy-menu");
		if(menu)
		{
			const logoutButton = document.createElement("button");
			logoutButton.textContent = "Logout";
			logoutButton.onclick = () => {logout()}
			menu.append(logoutButton);
		}

		// New interface
		const side_tb = document.querySelector(".side-tool-bar-end");
		const params_button = document.querySelector(".pi-cog");
		if(side_tb && params_button)
		{
			const logoutButton = params_button.parentElement.cloneNode(true);
			logoutButton.id = "bxRebootButtonNew";
			let shuticon = logoutButton.querySelector(".pi-cog");
			shuticon.classList.remove("pi-cog");
			shuticon.classList.add("pi-sign-out");
			side_tb.append(logoutButton);
			logoutButton.onclick = () => {logout()}
		}		
	},`

I made a fork to change UI but can't make PR as I removed parts I don't personnaly use....

**Comment by liusida** [comment]
Hi, syllebra, thanks. But I've just update to the latest version and I saw the Logout button right over there. Am I missing something?

![image](https://github.com/user-attachments/assets/85f3a534-664d-4fa1-9d8b-1fc80a9c1044)

**Comment by syllebra** [comment]
Did you activate the new UI in the settings?

![image](https://github.com/user-attachments/assets/ed18c4ff-bacd-4749-8a5c-9ecd62e551c7)

**Comment by liusida** [comment]
Thanks. I saw it.

**Comment by simeon49** [comment]
Sorry guys, I still no found the "logout" button in new UI, how to do it?
<img width="1668" alt="image" src="https://github.com/user-attachments/assets/5181cd9d-6972-46e2-8f78-701099eac6be">
![image](https://github.com/user-attachments/assets/72961b1a-09f8-4ed0-b631-d85fb4c025ac)

**Comment by syllebra** [comment]
Yes, it's a bug since a comfyui update. I just posted a fix. Update (git pull) and retry. Or wait for the package to be published.
