### ISSUE TITLE
api调用被login插件拦截问题

### ISSUE THREAD

**Issue by hhd-boospi** [liusida/ComfyUI-Login#3]
你好，我这边使用了login插件以后，api调用似乎就直接不通了，有办法兼容么？

**Comment by liusida** [comment]
我想想，这是一个好问题。

**Comment by liusida** [comment]
The value of `token` is the hashed password of your password, which stored in `./PASSWORD`. 

The `token` will change if you change your password. (which means you delete the `./PASSWORD` file and set a new password in the login page.
