### ISSUE TITLE
登录不进去，一直停留在登录界面

### ISSUE THREAD

**Issue by lldacing** [liusida/ComfyUI-Login#9]
![image](https://github.com/liusida/ComfyUI-Login/assets/43737696/00f56d77-4a21-4a22-9e7f-654fcc86c065)

**Comment by liusida** [comment]
Please help me to help you. Can you tell me what procedure you followed?

It might just be a wrong password. Could you try removing the login/PASSWORD file and setting the password again?

Also, is there a special character in your password? Try setting a simple password for testing. If any special character causes the system to break, please let me know. Thanks!

您能告诉我您遵循的是哪个程序吗？

可能只是密码错误。您能尝试删除 login/PASSWORD 文件并重新设置密码吗？

另外，您的密码中是否有特殊字符？尝试设置一个简单的密码进行测试。如果任何特殊字符导致系统出问题，请告诉我。谢谢！

**Comment by liusida** [comment]
close due to inactivity.
